name: audiodecoder.dumb build

on:
  pull_request

jobs:
  build:
    name: Windows
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Hello World"
        dir
        cd ..
        dir
        git clone --branch master --depth=1 https://github.com/xbmc/xbmc.git kodi
        #cd $(Build.SourcesDirectory)
        #mkdir build
        #cd build
        #mkdir "definition/$(app_id)"
        #echo $(app_id) . . > definition/$(app_id)/$(app_id).txt
        #mklink /J "$(Pipeline.Workspace)/$(app_id)" "$(Build.SourcesDirectory)"
