name: Binary addon build

on: pull_request

jobs:
  my-job:
    name: My Job
    runs-on: windows-2019

    steps:
    - name: Create addon
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo ${MY_VAR} 
        echo %FIRST_NAME%
        echo $(LAST_NAME).

