name: audiodecoder.dumb build

env:
  addon: audiodecoder.dumb

on:
  pull_request

jobs:
  build:
    name: Windows
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - run: |
        git clone --branch master --depth=1 https://github.com/xbmc/xbmc.git kodi
        cd $(addon)
        mkdir build
        cd build
        mkdir "definition/$(addon)"
        echo $(addon) . . > definition/$(addon)/$(addon).txt
        #mklink /J "$(Pipeline.Workspace)/$(app_id)" "$(Build.SourcesDirectory)"
